version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - streams
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=office2017.whistle.it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/office2017.whistle.it
    ports:
      - "8000:8000"
    networks:
      - streams
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_PASSWORD=Oneplus3t
      - DJANGO_SETTINGS_MODULE=web.settings.local
      - SOCKET_HOST=192.168.1.14
      - SOCKET_PORT=6969
  redis:
    image: "redis:alpine"
    networks:
      - streams
    ports:
      - "6379:6379"

#  pushpin:
#    image: fanout/pushpin
#    networks:
#      - streams
#    environment:
#      - "target=web:8000"
#      - "LOGNAME=nobody"
#    volumes:
#      - "./pushpin_routes:/etc/pushpin/routes"
#    depends_on:
#      - web
#    ports:
#      - "5561:5561"
#      - "5562:5562"
#      - "5563:5563"
#      - "7999:7999"

volumes:
  postgres_data:

networks:
  streams:
