version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - streams
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=edilcloud-back
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 web.asgi:application --settings=web.settings.production
    volumes:
      - .:/edilcloud-back
    ports:
      - "8000:8000"
    networks:
      - streams
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_PASSWORD=Oneplus3t
      - ENV_NAME=prod
      - SOCKET_HOST=35.178.108.7
      - SOCKET_PORT=6969
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - streams
  celery:
    build: .
    command: celery -A web worker -B --settings=web.settings.production
    environment:
      - ENV_NAME=prod
    networks:
      - streams
    volumes:
      - .:/edilcloud-back
    links:
      - db
      - redis

volumes:
  postgres_data:
  redis-data:
networks:
  streams: