version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - streams
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=office2017.whistle.it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 web.asgi:application
    volumes:
      - .:/office2017.whistle.it
    ports:
      - "8000:8000"
    networks:
      - streams
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_PASSWORD=Oneplus3t
      - SOCKET_HOST=35.176.179.55
      - SOCKET_PORT=6969

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - streams

  celery:
    build: .
    command: celery -A web worker -B
    networks:
      - streams
    volumes:
      - .:/code
    links:
      - db
      - redis

volumes:
  postgres_data:
  redis-data:
networks:
  streams:
    external: true