version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - streams
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=office2017.whistle.it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=web.settings.production
    volumes:
      - .:/office2017.whistle.it
    ports:
      - "8000:8000"
    networks:
      - streams
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_PASSWORD=Oneplus3t
      - SOCKET_HOST=3.9.185.8
      - SOCKET_PORT=6969
      - SOCKET_URL=https://ws.edilcloud.it
volumes:
  postgres_data:

networks:
  streams:
    external: true