version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - streams
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=edilcloud-back
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 web.asgi:application
    volumes:
      - .:/edilcloud-back
    ports:
      - "8000:8000"
    networks:
      - streams
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_PASSWORD=Oneplus3t
      - ENV_NAME=prod
      - SOCKET_HOST=18.130.248.158
      - SOCKET_PORT=6969
      - SOCKET_URL=https://ws.edilcloud.io

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - streams

  nginx:
    image: nginx:1.13
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
      args:
        - CERTBOT_EMAIL=monkeybits.srl@gmail.com
        - DOMAIN_LIST=edilcloud.io,*.edilcloud.io
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - web
      - db
    networks:
      - streams

  celery:
    build: .
    command: celery -A web worker -B
    networks:
      - streams
    volumes:
      - .:/edilcloud-back
    links:
      - db
      - redis

volumes:
  postgres_data:
  redis-data:
  letsencrypt:
networks:
  streams:
    external: true