version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - streams
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=office2017.whistle.it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=web.settings.production
    volumes:
      - .:/office2017.whistle.it
    ports:
      - "8000:8000"
    networks:
      - streams
    depends_on:
      - db
    environment:
      - SOCKET_HOST=35.176.179.55
      - SOCKET_PORT=6969

  nginx:
    image: nginx:1.13
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - db
    networks:
      - streams
volumes:
  postgres_data:

networks:
  streams:
    external: true