version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=office2017.whistle.it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/office2017.whistle.it
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: